app:
  debug: false
  host: 0.0.0.0
  name: YT-DLP Web
  port: 8090
  secret_key: PLEASE-CHANGE-THIS-SECRET-KEY-BEFORE-PRODUCTION
  version: 2.0.0
auth:
  default_password: CHANGE-ME-ON-FIRST-LOGIN
  default_username: admin
  session_timeout: 86400
database:
  echo: false
  url: sqlite:///data/app.db
downloader:
  auto_cleanup: true
  cleanup_interval: 3600
  file_retention_hours: 168
  keep_recent_files: 20
  max_concurrent: 3
  max_file_age: 86400
  max_storage_mb: 5000
  output_dir: data/downloads
  temp_dir: data/temp
  timeout: 300
features:
  ai_analysis: false
  cloud_storage: false
  monitoring: false
  multi_user: false
  plugins: false
logging:
  backup_count: 5
  file: data/logs/app.log
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
  max_size: 10485760
network:
  connect_timeout: 30
  max_retries: 3
  read_timeout: 60
  retry_delay: 1
  user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
proxy:
  enabled: false
  host: ''
  password: ''
  port: null
  proxy_type: http
  username: ''
security:
  allowed_origins: []
  api_enabled: true
  api_key: 0Wv5HIKz1e5TbEM4cie7rUEEgDy9DNMY
  cors_enabled: false
storage:
  cleanup_enabled: true
  cleanup_schedule: 0 2 * * *
  max_disk_usage: 80
  min_free_space: 1024
telegram:
  api_hash: ''
  api_id: null
  auto_download: true
  bot_token: ''
  chat_id: ''
  enabled: false
  file_size_limit: 40  # Bot API 实际限制约 40MB，大文件需要 Pyrofork
  push_mode: file
  webhook_url: ''
  # 注意：当前网络环境下 Pyrofork 无法连接，仅支持 ≤40MB 文件上传
ytdlp:
  auto_update: true
  extract_flat: false
  format: bestvideo[height<=2160]+bestaudio/best[height<=2160]/best
  source: github
  version: latest
