# YT-DLP Web WARP版 Docker Compose 配置模板
# 使用前请修改所有标记为 "请修改" 的配置项

services:
  yt-dlp-web:
    image: ghcr.io/your-username/yt-dlp-web-warp:latest  # 请修改为您的镜像地址
    container_name: yt-dlp-web-warp
    restart: unless-stopped
    ports:
      - "8090:8080"  # 请根据需要修改外部端口
    
    # WARP 需要的特殊权限
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
    
    volumes:
      # 配置文件持久化 - 请修改路径
      - /your-path/yt-dlp-web/config/:/app/config
      # 数据库持久化 - 请修改路径
      - /your-path/yt-dlp-web/data/:/app/data
      # 日志持久化 - 请修改路径
      - /your-path/yt-dlp-web/logs/:/app/logs
      # WARP 数据持久化 - 请修改路径
      - /your-path/yt-dlp-web/warp/:/var/lib/cloudflare-warp
      
      # 开发调试用（生产环境请删除）
      # - /your-path/yt-dlp-web/code/app/:/app
      
    environment:
      # 基础配置
      - FLASK_ENV=production  # 生产环境，开发环境改为 development
      - SECRET_KEY=please-change-this-secret-key-to-a-random-string  # 请修改为随机字符串
      
      # WARP 配置
      - ENABLE_WARP=true
      - WARP_PROXY_PORT=1080  # 可根据需要修改端口
      - WARP_LICENSE_KEY=  # 可选：填入您的 WARP+ 许可证
      
      # 管理员账号配置 - 请修改
      - ADMIN_USERNAME=admin  # 请修改管理员用户名
      - ADMIN_PASSWORD=please-change-this-password  # 请修改管理员密码
      
      # 数据库配置
      - DATABASE_URL=sqlite:///data/app.db
      
      # 下载配置
      - DOWNLOAD_DIR=/app/downloads
      - MAX_CONCURRENT=3  # 可根据服务器性能调整
      
      # Telegram配置 (可选) - 请填入您的配置
      - TELEGRAM_BOT_TOKEN=  # 请填入您的 Bot Token
      - TELEGRAM_CHAT_ID=    # 请填入您的 Chat ID
      - TELEGRAM_API_ID=     # 请填入您的 API ID
      - TELEGRAM_API_HASH=   # 请填入您的 API Hash
      
      # 时区设置 - 请根据需要修改
      - TZ=Asia/Shanghai
      
      # 开发调试配置（生产环境请删除或设为0）
      - FLASK_DEBUG=0
      - PYTHONPATH=/app
      
    networks:
      - yt-dlp-network
    labels:
      # Portainer管理标签
      - "io.portainer.accesscontrol.teams=administrators"
      - "io.portainer.accesscontrol.users=admin"
      # 应用信息标签
      - "app.name=yt-dlp-web-warp"
      - "app.description=YouTube视频下载器Web界面(WARP版)"
      - "app.version=2.0.0-warp"
      - "app.category=media"
      - "app.url=http://localhost:8090"  # 请根据实际端口修改
      # 健康检查标签
      - "health.check.url=http://localhost:8090/api/health"  # 请根据实际端口修改
      - "health.check.interval=30s"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 100s
      timeout: 10s
      retries: 3
      start_period: 120s  # WARP 版需要更长启动时间

networks:
  yt-dlp-network:
    driver: bridge
    labels:
      - "app.network=yt-dlp"
