# YT-DLP Web Docker Compose 示例配置
version: '3.8'

services:
  # 标准版本（默认）
  yt-dlp-web:
    image: ghcr.io/your-username/yt-dlp-web:latest
    container_name: yt-dlp-web
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SECRET_KEY=change-this-secret-key-in-production
    volumes:
      - ./data:/app/data
      - ./downloads:/app/downloads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # WARP 版本（取消注释以启用）
  # yt-dlp-web-warp:
  #   image: ghcr.io/your-username/yt-dlp-web-warp:latest
  #   container_name: yt-dlp-web-warp
  #   restart: always
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - SECRET_KEY=change-this-secret-key-in-production
  #     - ENABLE_WARP=true
  #     - WARP_PROXY_PORT=1080
  #     - WARP_LICENSE_KEY=  # 可选：WARP+ 许可证
  #   cap_add:
  #     - NET_ADMIN
  #   sysctls:
  #     - net.ipv4.ip_forward=1
  #     - net.ipv4.conf.all.src_valid_mark=1
  #     - net.ipv6.conf.all.disable_ipv6=0
  #     - net.ipv6.conf.all.forwarding=1
  #   volumes:
  #     - ./data:/app/data
  #     - ./downloads:/app/downloads
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 60s  # WARP 需要更长启动时间

volumes:
  data:
    driver: local
  downloads:
    driver: local
